# Generated by Django 3.2.7 on 2022-01-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=5000)),
                ('review_date', models.DateTimeField(verbose_name='Date published')),
                ('review_user', models.CharField(max_length=100)),
                ('review_book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fluffyBooks.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluffyBooks.genre'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_text', models.CharField(max_length=200)),
                ('books', models.ManyToManyField(blank=True, to='fluffyBooks.Book')),
            ],
        ),
    ]
