# Generated by Django 3.2.7 on 2022-02-04 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluffyBooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userlikes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
