# Generated by Django 3.2.7 on 2022-02-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0003_auto_20220219_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fluffyBooks.author'),
        ),
    ]
