# Generated by Django 3.2.7 on 2022-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0004_auto_20220219_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(blank=True, to='fluffyBooks.Author'),
        ),
    ]
