# Generated by Django 4.0.4 on 2022-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0006_auto_20220221_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_books',
            field=models.ManyToManyField(blank=True, to='fluffyBooks.book'),
        ),
    ]
