# Generated by Django 4.0.4 on 2022-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0007_author_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genre',
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ManyToManyField(blank=True, to='fluffyBooks.genre'),
        ),
    ]
