# Generated by Django 4.0.4 on 2022-04-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0008_remove_book_book_genre_book_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_genre',
            new_name='book_genres',
        ),
    ]
