# Generated by Django 4.0.4 on 2022-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluffyBooks', '0009_rename_book_genre_book_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_books',
        ),
    ]
